AXF_Project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from axf.views import yx

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),
    url(r"^$",yx)
    # url(r'^axf/api/v1/',include('axf.urls_apis_v1',namespace='axfapi'))
]

axf/urls.py
from django.conf.urls import urlfrom .views import *urlpatterns = [    url(r'^home$',home,name='home'),    url(r'^cart$',cart,name='cart'),    url(r'^market$',market,name='market'),    url(r'^market_with_params/(\d+)/(\d+)/(\d+)',market_with_params,name='market_with_params'),    url(r'^mine$',mine,name='mine'),    url(r'^register$',RegisterAPI.as_view(),name='register'),    url(r'^login$',LoginAPI.as_view(),name='login'),    url(r'^confirm/(.*)',confirm),    url(r'^logout$',logout_api,name='logout'),    url(r'^cartapi$',cart_api,name='cart_api'),    url(r'^cart_status$',cart_status_api),    url(r'^select_all_api$',select_all_api),    url(r'^cartitem_api$',cartitem_api),    url(r'^order$',order_api,name='order'),    url(r'^123$',heike),    # url(r'^2048$',yx)]

templates/base/base.html
<!DOCTYPE html>{%load static%}<html lang="en"><head>    <meta charset="UTF-8">    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">    <link rel="stylesheet" href="{%static 'css/swiper.css'%}">    <link rel="stylesheet" href="{%static 'css/reset.css'%}">    {% block css %}    {% endblock %}    <title>{{ title }}</title></head><body>{% block header %}{% endblock %}{% block content %}{% endblock %}{% block footer %}{% endblock %}</body>    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>    {% block js %}    {% endblock %}</html>

templates/base/base_main.html
{% extends 'base/base.html' %}{% load static %}{% block css %}    {{ block.super }}    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">{% endblock %}{% block header %}    <header></header>{% endblock %}{% block content %}    <content></content>{% endblock %}{% block footer %}    <footer>        <a href="{% url 'axf:home' %}" class="home">            <dl>                <dt>                    <span></span>                </dt>                <dd>首页</dd>            </dl>        </a>        <a href="{% url 'axf:market' %}" class="market">            <dl>                <dt>                    <span></span>                </dt>                <dd>闪购</dd>            </dl>        </a>        <a href="{% url 'axf:cart' %}" class="cart">            <dl>                <dt>                    <span></span>                </dt>                <dd>购物车</dd>            </dl>        </a>        <a href="{% url 'axf:mine' %}" class="mine">            <dl>                <dt>                    <span></span>                </dt>                <dd>我的</dd>            </dl>        </a>    </footer>{% endblock %}

templates/base/base_user.html
{% extends 'base/base.html' %}{% load static %}{% block css %}    {{ block.supper }}    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">{% endblock %}{% block header %}    <header></header>{% endblock %}