AXF_Project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from axf.views import yx

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),
    url(r"^$",yx)
    # url(r'^axf/api/v1/',include('axf.urls_apis_v1',namespace='axfapi'))
]

axf/urls.py
from django.conf.urls import urlfrom .views import *urlpatterns = [    url(r'^home$',home,name='home'),    url(r'^cart$',cart,name='cart'),    url(r'^market$',market,name='market'),    url(r'^market_with_params/(\d+)/(\d+)/(\d+)',market_with_params,name='market_with_params'),    url(r'^mine$',mine,name='mine'),    url(r'^register$',RegisterAPI.as_view(),name='register'),    url(r'^login$',LoginAPI.as_view(),name='login'),    url(r'^confirm/(.*)',confirm),    url(r'^logout$',logout_api,name='logout'),    url(r'^cartapi$',cart_api,name='cart_api'),    url(r'^cart_status$',cart_status_api),    url(r'^select_all_api$',select_all_api),    url(r'^cartitem_api$',cartitem_api),    url(r'^order$',order_api,name='order'),    url(r'^123$',heike),    # url(r'^2048$',yx)]

templates/user/login.html
{% extends 'base/base_user.html' %}{% load static %}{% block content %}    <div class="container">        <form action="{% url 'axf:login' %}" method="post">            <div class="form-group">                <label for="exampleInputEmail1">用户名</label>                <input type="text" class="form-control" id="name_id" placeholder="输入用户名" name="uname">            </div>            <div class="form-group">                <label for="exampleInputPassword1">密码</label>                <input type="password" class="form-control" id="pwd_id" placeholder="输入密码" name="pwd">            </div>            <button type="submit" class="btn btn-success btn-block">登录</button>        </form>    </div>{% endblock %}{% block js %}    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>    <script type="text/javascript" src="{% static 'axf/user/js/login.js' %}"></script>{% endblock %}

templates/user/register.html
{% extends 'base/base_user.html' %}{% load static %}{% block content %}    <div class="container">        <form action="{% url 'axf:register' %}" method="post" enctype="multipart/form-data">            <div class="form-group">                <label for="exampleInputEmail1">用户名</label>                <input type="text" class="form-control" id="name_id" placeholder="输入用户名" name="uname">            </div>            <div class="form-group">                <label for="exampleInputPassword1">密码</label>                <input type="password" class="form-control" id="pwd_id" placeholder="输入密码" name="pwd">            </div>            <div class="form-group">                <label for="exampleInputEmail1">确认密码</label>                <input type="password" class="form-control" id="c_pwd_id" placeholder="确认密码" name="c_pwd">            </div>            <div class="form-group">                <label for="exampleInputEmail1">邮箱</label>                <input type="email" class="form-control" id="email_id" placeholder="输入邮箱" name="email">            </div>            <div class="form-group">                <label for="exampleInputFile">选择头像</label>                <input type="file" id="imgicon" name="icon">            </div>            <button type="submit" class="btn btn-success btn-block">注册</button>        </form>    </div>{% endblock %}{% block js %}    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>    <script type="text/javascript" src="{% static 'axf/user/js/register.js' %}"></script>{% endblock %}

templates/user/user_confirm.html
<!DOCTYPE html><html lang="en"><head>    <meta charset="UTF-8">    <title>1808会员激活</title></head><body>    欢迎加入1808club，点击下面链接完成验证(如非本人操作 请忽略)    <br/>    <a href="{{ url }}">{{ url }}</a></body></html>